import { PerfumeProps } from "./perfume";

// Function to generate a random number between min and max (inclusive)
function getRandomNumber(min: number, max: number): number {
    return Math.floor(Math.random() * (max - min + 1) + min);
  }
  
  // Function to create an array of PerfumeProps
export function getPerfumeFromLocal(): PerfumeProps[] {
    const names = [
        "Infusion d'Homme",
        "Luna Rossa Ocean",
        "L'Homme",
        "Candy",
        "Candy Kiss",
        "Candy Gloss",
        "Bonne Étoile Baby Dior",
        "Eau de Cologne aux Fleurs Fraiches",
        "Eau de Cologne Fraîche",
        "Cruise Collection Escale a Parati",
        "Eau Sauvage 100% Glaçon",
        "The Cachemire ",
        "Alpha",
        "Untitled Humans",
        "The Perfection",
         "Amber Pour Homme",
        "La Femme",
         "L'Homme Intense",
        "Pour Homme Dylan Blue",
        "Pour Homme",
        "Pour Homme Oud Noir",
        "Eros",
        "Eros Flame",
        "Pour femme Dylan Purple",
        "Do Son",
        "Olene",
        "Volutes",
        "Eau Capitale",
        "Fleur de Peau",
        "Philosykos ",
        "Ameer Al Oudh Intense Oud",
        "Raghba",
        "Oud Mood",
        "Fakhar Black",
        "Ana Abiyedh",
        "Bade'e Al Oud Honor & Glory",
    ]; // List of perfume names
    const images = [
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Prada_Infusiond_Homme.jpg?alt=media&token=51a6e28a-f52a-4d1a-a07b-5433eb38a524",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Prada_LunaRossaOcean.jpg?alt=media&token=b33498d4-215c-4417-83ec-d57e28b8a5a1",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Prada_L_Homme.jpg?alt=media&token=d8f820e1-5243-4010-a658-c2c55366757f",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Prada_Candy.jpg?alt=media&token=954b6e01-f64e-4f89-84ff-3f601aff0124",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Prada_CandyKiss.jpg?alt=media&token=45537bff-1d39-4a1c-9d48-0fc2e0c3b163",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Prada_CandyGloss.jpg?alt=media&token=8fdd2f15-eccf-4de4-a4e3-6d7d618ce062",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/DIor_Bonne%20%C3%89toile%20Baby%20Dior.jpg?alt=media&token=3f3a5455-5718-41de-b34f-f0970a1d1992",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Dior_Eau%20de%20Cologne%20aux%20Fleurs%20Fraiches.jpg?alt=media&token=a15c7c09-45df-40c1-bfd9-080c07a189e7",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Dior_Eau%20de%20Cologne%20Fra%C3%AEche.jpg?alt=media&token=1e6a7e42-d3a5-4b31-82ee-655b9d0cf880",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Dior_Criuse%20Collection%20Escale%20a%20Parati.jpg?alt=media&token=ff86cba0-1f00-4a1f-a966-8667948d6b6f",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Dior_Eau%20Sauvage%20100_%20Gla%C3%A7on.jpg?alt=media&token=f43655ad-5b84-439e-981d-b4a002336f37",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Dior_The%20Cachemire.jpg?alt=media&token=1876726c-86b9-4be0-afa9-846fec8e0af5",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/HMNS_Alpha.jpg?alt=media&token=6d856bf8-1bde-4ba6-92c5-82b86e8ac844",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/HMNS_Untitled%20Humans.jpg?alt=media&token=72d66640-0565-4ef2-9f82-c20087dbed4d",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/HMNS_The%20Perfection.jpg?alt=media&token=28758020-72b7-4c99-b3f8-709a6c7d1489",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Prada_%20Amber%20Pour%20Homme.jpg?alt=media&token=ea95b6d8-2025-404c-a4f7-49c7f6dc58a5",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Prada_La%20Femme.jpg?alt=media&token=ec1224c9-a942-4de3-9470-094cbfab1abe",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Prada_%20L_Homme%20Intense.jpg?alt=media&token=2a95f90f-08da-4a95-99fa-29f4988eeebc",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Versace_PourHommeDylanBlue.jpg?alt=media&token=af0b5372-25ec-4c99-8109-96dc7fd6b30b",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Versace_PourHomme.jpg?alt=media&token=b98ca41b-1cc6-45f2-934a-efd025b687e8",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Versace_PourHommeOudNoir.jpg?alt=media&token=51043a16-6482-47e3-ba3a-c418dbd80a9f",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Versace_Eros.jpg?alt=media&token=f7d9b5d1-3df2-4733-b11b-70dfbe56aab8",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Versace_ErosFlame.jpg?alt=media&token=438bc1a1-45c9-424e-a405-2e9e39d0e783",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Versace_PourFemmeDylanPurple.jpg?alt=media&token=f9f6bbaa-2326-448d-a9a7-349f97e2aecd",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Diptyque_Do%20Son.jpg?alt=media&token=2c6736bb-a290-4591-b8a2-bc3fd6a7916c",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Diptyque_Olene.jpg?alt=media&token=fda4ea24-a4e8-4c37-8599-f3532cf8616d",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Diptyque_Volutes.jpg?alt=media&token=47e820db-e8f8-46ca-8bba-e7caf959f2c2",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Diptyque_Eau%20Capitale.jpg?alt=media&token=89b19398-9568-407c-82af-f8afd14fe7a9",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Diptyque_Fleur%20de%20Peau.jpg?alt=media&token=2564caa9-ef86-4b36-a25f-e35b6dc5f5a2",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Diptyque_Philosykos%20.jpg?alt=media&token=96b04654-6cca-4de6-b149-0d27e9bfb7ef",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Lattafa_Ameer%20Al%20Oudh%20Intense%20Oud.jpg?alt=media&token=7da0a2f0-ea2d-4b26-ae0c-4b9552d1010a",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Lattafa_Raghba.jpg?alt=media&token=eaa02e24-a2d6-46ce-bf88-8178dc3e8dc5",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Lattafa_Oud%20Mood.jpg?alt=media&token=07937bc3-7cbf-4caf-8851-c3353ef27d92",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Lattafa_Fakhar%20Black.jpg?alt=media&token=3ad620e8-048d-4cec-913a-bb4b1e0538e1",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Lattafa_Ana%20Abiyedh.jpg?alt=media&token=806c5613-c6e8-46a1-9564-081d4a7b9f67",
        "https://firebasestorage.googleapis.com/v0/b/elixir-8ce95.appspot.com/o/Lattafa_Bade_e%20Al%20Oud%20Honor%20_%20Glory.jpg?alt=media&token=5a198526-7525-4d2c-acd1-03e9966861e0",
    ]; // List of image URLs
    const prices = [
        1499000,
        1240000,
        3480000,
        1850000,
        2450000,
        1999000,
        149000,
        129000,
        129000,
        179000,
        169000,
        259000,
        320000,
        395000,
        398000,
        1790000,
        2363759,
        1695000,
        1640000,
        1640000,
        2413727,
        1640000,
        1866000,
        1979000,
        3575000,
        2719500,
        1585841,
        3448723,
        2798000,
        1087800,
        259000,
        195000,
        219000,
        280000,
        190000,
        349000,
    ]; // List of prices
    const brands = [
        "Prada",
        "Prada",
        "Prada",
        "Prada",
        "Prada",
        "Prada",
        "Dior",
        "Dior",
        "Dior",
        "Dior",
        "Dior",
        "Dior",
        "HMNS",
        "HMNS",
        "HMNS",
        "Prada",
        "Prada",
        "Prada",
        "Versace",
        "Versace",
        "Versace",
        "Versace",
        "Versace",
        "Versace",
        "Diptyque",
        "Diptyque",
        "Diptyque",
        "Diptyque",
        "Diptyque",
        "Diptyque",
        "Lattafa",
        "Lattafa",
        "Lattafa",
        "Lattafa",
        "Lattafa",
        "Lattafa",
    ]; // List of brands
    const occasions = [
        "Versatile",
        "Versatile",
        "Versatile",
        "Versatile",
        "Versatile",
        "Versatile",
        "Versatile",
        "Versatile",
        "Versatile",
        "Versatile",
        "Versatile",
        "Versatile",
        "Versatile",
        "Night",
        "Versatile",
        "Night",
        "Night",
        "Versatile",
        "Versatile",
        "Versatile",
        "Versatile",
        "Night",
        "Night",
        "Day",
        "Day",
        "Day",
        "Versatile",
        "Versatile",
        "Versatile",
        "Day",
        "Night",
        "Night",
        "Night",
        "Day",
        "Day",
        "Day",
    ]; // List of occasions
    const sizes = [
        100,
100,
100,
50,
50,
50,
100,
100,
100,
100,
100,
100,
100,
100,
100,
100,
100,
100,
100,
100,
100,
100,
100,
100,
100,
100,
100,
50,
50,
50,
100,
100,
100,
100,
100,
100,
    ]; // List of sizes
    const concentrations = [
        "Eau de Toilette",
        "Eau de Toilette",
        "Eau de Toilette",
        "Eau de Parfum",
        "Eau de Parfum",
        "Eau de Toilette",
        "Eau de Toilette",
        "Eau de Toilette",
        "Eau de Parfum",
        "Eau de Toilette",
        "Eau de Toilette",
        "Eau de Parfum",
        "Eau de Parfum",
        "Eau de Parfum",
        "Eau de Parfum",
        "Eau de Toilette",
        "Eau de Parfum",
        "Eau de Parfum",
        "Eau de Toilette",
        "Eau de Toilette",
        "Eau de Parfum",
        "Eau de Toilette",
        "Eau de Parfum",
        "Eau de Parfum",
        "Eau de Toilette",
        "Eau de Toilette",
        "Eau de Toilette",
        "Eau de Parfum",
        "Eau de Parfum",
        "Eau de Parfum",
        "Extrait de Parfum",
        "Extrait de Parfum",
        "Extrait de Parfum",
        "Eau de Parfum",
        "Eau de Parfum",
        "Eau de Parfum",
    ]; // List of concentrations
    const origins = [
        "Italy",
        "Italy",
        "Italy",
        "Italy",
        "Italy",
        "Italy",
        "France",
        "France",
        "France",
        "France",
        "France",
        "France",
        "Indonesia",
        "Indonesia",
        "Indonesia",
        "Italy",
        "Italy",
        "Italy",
        "Italy",
        "Italy",
        "Italy",
        "Italy",
        "Italy",
        "Italy",
        "France",
        "France",
        "France",
        "France",
        "France",
        "France",
        "UEA",
        "UEA",
        "UEA",
        "UEA",
        "UEA",
        "UEA",
    ]; // List of origins
    const topNotes = [
        "Neroli, Mandarin Orange",
        "Bergamot, Pink Pepper, Artemisia",
        "Neroli, Black Pepper, Cardamom, Carrot Seeds",
        "Caramel",
        "Musk",
        "Sour Cherry, Cassis",
        "Green Pear",
        "Lemon, Lemon Verbena",
        "Lemon, Lemon Verbena",
        "Petitgrain, Lemon, Bitter Orange",
        "Citruses, Lemon, Basil, ",
        "Fruity Notes, Mint",
        "Petitgrain, Bergamot, Lemon ,Bitter Orange",
        "Citrus, Grass",
        "Coriander, Violet leaves, Ambrette",
        "Bergamot, Elemi, Indonesian Clove, Nutmeg",
        "Neroli, Cardamom, Bergamot, ",
        "Mandarin Orange",
        "Magnolia, Bergamot, Carrot Seeds",
        "Iris",
        "Calabrian bergamot, Water Notes, ",
        "Grapefruit, Fig Leaf",
        "Lemon, Bergamot, Neroli, Rose de Mai",
        "Black Pepper, Bitter Orange, Neroli",
        "Mint, Green Apple, Lemon",
        "Mandarin Orange, Madagascar Pepper, ",
        "Lemon, Chinotto, Rosemary",
        "Pear, Bitter Orange, Bergamot",
        "African Orange Flower, Iris, Rose",
        "Narcissus, Honersuckle",
        "Tobacco, Honey, Iris, Dried Fruits",
        "Pink Pepper, Bergamot",
        "Aldehydes, Pink Pepper, Angelica, Bergamot",
        "Fig Leaf, Fig",
        "Woodsy Notes, Agarwood",
        "Vanilla, Sugar",
        "Rose, Saffron, Pimento",
        "Apple, Bergamot, Ginger",
        "Bergamot, Orange",
        "Pineapple, Creme Brulee",
    ]; // List of top notes arrays
    const middleNotes = [
"Iris, Vetiver, Galbanum, Ceda",
"Lavender, Iris, Sage, Suede, Saffron",
"Iris, Violet, Geranium, Mate",
"Powdery Notes, Musk",
"Musk, Orange Blossom",
"Peach, Rose, Orange Blossom",
"Wild Rose",
"Jasmine, Rose Water and ",
"Lily of the Valley",
"Palisander Rosewood, Jasmine, Rose",
"Mint, Palisander Rosewood, ",
"Cinnamon, Red Berries",
"Rose, Orris Root, Coriander, Patchouli",
"White Tea, Hedione, Honeysuckle, ",
"Black Currant, Magnolia, Rose",
"Green Tea, Wood",
"Figolide, Velvet, Rose Absolute",
"Lavender, Tagetes, Lily of the Valley, ",
"Green Pear",
"Myrrh, Musk, Orange Blossom, ",
"Geranium, Vetiver",
"Frangipani, Tuberose, Ylang-Ylang,",
"Iris, Spices",
"Amber, Patchouli",
"Ambroxan, Black Pepper, Patchouli, ",
"Violet Leaf, Papyrus",
"Hyacinth, Cedar, Clary Sage, ",
"Geranium",
"Saffron, Cardamom, Olibanum",
"Tonka Bean, Ambroxan, Geranium",
"Geranium, Rose, Pepperwood",
"Freesia, Pomarose, Mahonial",
"Tuberose, Pink Pepper",
"Jasmine, Wisteria",
"Hay, Immortelle, Saffron, Pink Pepper, Black Pepper",
"Rose",
"Iris, Turkish Rose",
"Green Notes, Coconut",
"Sugar, Vanilla",
"Agarwood, Incense",
"Agarwood, Caramel, Floral Notes, Patchouli",
"Lavender, Sage, Juniper Berries, Geranium",
"Vanilla, Pear",
"Cinnamon, Benzoin, Turmeric, Black Pepper",
    ]; // List of middle notes arrays
    const baseNotes = [
        "Powdery Notes, Olibanum, Benzoin",
        "Musk, Haitian Vetiver, Caramel, Patchouli",
        "Amber, Cedar, Patchouli, Sandalwood",
        "Benzoin, Vanilla",
        "Musk, Vanilla",
        "Vanilla, Almond, Benzoin, Heliotrope, Musk",
        "White Musk",
        "Oakmoss",
        "Oakmoss, Patchouli",
        "Woodsy Notes, Tonka Bean",
        "Amber, Musk",
        "Mate, Musk, Iso E Super, Smoke, Orris",
        "Cedarwood, Vetiver",
        "Sandalwood, Cypriol,",
        "Vanilla Jungle Essence",
        "Driftwood, Sandalwood, ",
        "Leather, Musky",
        "Saffron, Vanilla, Labdanu, Tonka Bean, ",
        "Leather, Sandalwood, Patchouli",
        "Beeswax, Vanilla, Vertiver",
        "Tonka Bean, Leather, Sandalwood",
        "Incense, Musk, Tonka Bean, Saffron",
        "Tonka Bean, Musk, Amber",
        "Agarwood, Patchouli, ",
        "Leatherwood",
        "Madagascar Vanilla, Virginian Cedar, ",
        "Atlas Cedar, Vetiver, Oakmoss",
        "Vanilla, Tonka Bean, Sandalwood, ",
        "Texas Cedar, Patchouli, Oakmoss",
        "Ambroxan, Iso E Super, Sylkolide, ",
        "Virginia Cedar, Belambra tree",
        "Benzoin, Musk",
        "White Flowers, Green Notes",
        "Benzoin, Opoponax, Myrhh, Styrax",
        "Patchouli",
        "Musk, Ambrette, Carrot, Ambergris, Sandalwood, Leather, Amberwood",
        "Fig Tree, Woody Notes, Cedar",
        "Agarwood, Sandalwood, Herbal Notes",
        "Sandalwood, Mush",
        "Resins, Woody Notes, Amber, Incense, Musk",
        "Tonka Bean, Amberwood, Cedar, Vetiver",
        "Musk, Amber",
        "Vanilla, Cashmeran, Sandalwood, Moss",
    ]; // List of base notes arrays
    const genders = [
        "Men",
        "Men",
        "Men",
        "Women",
        "Women",
        "Women",
        "Unisex",
        "Unisex",
        "Unisex",
        "Unisex",
        "Unisex",
        "Unisex",
        "Men",
        "Unisex",
        "Men",
        "Men",
        "Women",
        "Men",
        "Men",
        "Men",
        "Men",
        "Men",
        "Men",
        "Women",
        "Women",
        "Women",
        "Women",
        "Unisex",
        "Unisex",
        "Unisex",
        "Unisex",
        "Unisex",
        "Unisex",
        "Men",
        "Unisex",
        "Unisex",
    ]; // List of genders
    const descriptions = [
        "Infusion d'Homme is a modern and sophisticated fragrance that is both refreshing and elegant. It opens with a bright and citrusy top note of neroli, followed by a heart of powdery iris and earthy vetiver. The base is warm and woody, with notes of olibanum, benzoin, and cedar.",
        "Luna Rossa Ocean is a fragrance for men that captures the essence of the sea. It is a fresh and invigorating scent that is perfect for everyday wear. The fragrance opens with a bright cocktail of bergamot, contrasted with the extreme sophistication and sensuality of vetiver and elegant iris notes.",
        "Prada L'Homme is a fragrance that reflects the duality of the masculine identity. It is both classic and contemporary, sensual and sophisticated. The fragrance is composed of a blend of classic ingredients, such as neroli, geranium, and patchouli, with a contemporary accent. This makes it a versatile fragrance that can be worn for any occasion.",
        "Prada Candy is a fragrance that embodies the spirit of youthful rebellion and the allure of forbidden indulgence. It is a captivating blend of caramel, benzoin, and musk that is both sweet and sensual. The fragrance is housed in a luxurious gold bottle that is adorned with a pink Saffiano leather bow.",
        "Prada Candy Kiss is an irresistible eau de parfum that encapsulates the essence of modern femininity. This captivating fragrance is a symphony of contrasts, where sparkling bergamot meets luscious orange blossom notes, creating an unexpected olfactory balance. The scent is further enriched with a powdery vanilla accord, leaving an alluring trail that lingers long after the first spritz.",
        "Prada Candy Gloss is a sparkling and intensely joyful fragrance that captures the essence of feminine allure. It is a sensual sorbet, sweet as acid cherry and solar as the orange blossom. The fragrance opens with notes of mandarin, raspberry, and benzoin, followed by a heart of rose, orange blossom, and musk. The base of the fragrance is composed of vanilla, musk, and sandalwood.",
        "Bonne Étoile Baby Dior is a fresh, floral fragrance for babies and young children. It is designed to be gentle and soothing, with a light, airy scent. The top notes of mandarin orange, bergamot, and lemon are bright and uplifting, while the middle notes of jasmine, rose, and lily of the valley add a touch of sweetness. The base notes of white musk, patchouli, and sandalwood provide a warm, comforting finish. ",
        "Eau de Cologne aux Fleurs Fraiches is a classic, unisex fragrance that has been around since the 1950s. It is a fresh, floral scent with a clean, crisp feel. The top notes of lemon and verbena are bright and invigorating, while the middle notes of jasmine, rose water, and lily of the valley add a touch of sweetness and sophistication. The base note of oakmoss provides a warm, grounding finish.",
        "Eau de Cologne Fraîche is a fresh, citrusy fragrance for men and women. It is a light, airy scent that is perfect for everyday wear. The top notes of citrus and bergamot are bright and refreshing, while the middle notes of jasmine, rose, and lily of the valley add a touch of sweetness. The base notes of musk and sandalwood provide a warm, comforting finish. ",
        "Cruise Collection Escale a Parati is a tropical, floral fragrance for women. It is a vibrant, inviting scent that is perfect for a summer vacation. The top notes of citrus, pineapple, and coconut are bright and refreshing, while the middle notes of jasmine, tuberose, and frangipani add a touch of tropical sweetness. The base notes of sandalwood, amber, and patchouli provide a warm, sensual finish. ",
        "Eau Sauvage 100% Glaçon is a fresh, aquatic fragrance for men. It is a modern take on the classic Eau Sauvage fragrance, with a bolder, more intense scent. The top notes of grapefruit, bergamot, and lemon are bright and refreshing, while the middle notes of lavender, geranium, and rosemary add a touch of herbal complexity. The base notes of patchouli, oakmoss, and vetiver provide a warm, woody finish. ",
        "The Cachemire is a luxurious, sensual fragrance for women. It is a warm, enveloping scent that is perfect for a special occasion. The top notes of bergamot, mandarin orange, and lemon are bright and refreshing, while the middle notes of jasmine, rose, and lily of the valley add a touch of sweetness. The base notes of cashmere, sandalwood, and musk provide a warm, sensual finish. ",
        "HMNS Perfume Alpha is a fresh and calming fragrance that is perfect for everyday wear. It features top notes of citrus and grass, middle notes of cedarwood, and base notes of green tea essence. The result is a scent that is both invigorating and relaxing.",
        "Untitled Humans is a unisex eau de parfum fragrance created by HMNS in collaboration with Maliq & D'Essentials. The fragrance is designed to celebrate individuality and freedom of self-expression, and it is inspired by the idea that humans are too complex to be labeled.",
        "HMNS Perfume The Perfection is a spicy-fougere fragrance that was created in collaboration with Christian Sugiono. It is designed to provide a luxurious and clean sensation that is perfect for any important event or as your signature scent. The fragrance went through 145 trials before reaching its final form, which is a testament to the dedication and craftsmanship that went into its creation.",
        "Prada Amber Pour Homme is a rich and complex fragrance that intermingles the clean, fresh scent of barber's soap with a warm, seductive amber accord. It is a fragrance for the modern man who is both sophisticated and adventurous.",
        "Prada La Femme is a modern, radiant, and subtly seductive fragrance that celebrates the multifaceted nature of femininity. It is a floral fragrance with a touch of spice and honey, making it both elegant and sensual.",
        "Prada L'Homme Intense is a woody, oriental fragrance for men. It was launched in 2017 and is the more intense version of the original Prada L'Homme. The fragrance is described as being \"a multi-layered experience\" that enhances the scent of iris and amber with notes of leather and patchouli, while tonka bean gives it an oriental signature. The goal of the scent and its opaque bottle is to evoke \"the elusive nature of the multi-faceted Prada man.\"",
        "Versace Pour Homme Dylan Blue is a captivating fragrance that embodies the allure of the Mediterranean Sea. With its opening notes of Calabrian bergamot, grapefruit, and aquatic accords, it transports you to a sun-drenched coastal paradise. The heart of the fragrance unveils a symphony of ambroxan, black pepper, patchouli, violet leaf, and papyrus, adding a touch of intrigue and depth. As the fragrance settles, a warm embrace of incense, musk, tonka bean, and saffron envelops you, leaving an indelible mark of sophisticated masculinity.",
        "Versace Pour Homme is a timeless classic that exudes elegance and sophistication. Its opening citrus burst of lemon, bergamot, and mandarin orange awakens the senses, while the heart of jasmine, rose, and geranium adds a touch of refinement. The concluding notes of amber, sandalwood, and musk provide a lingering warmth that speaks to the enduring legacy of this iconic fragrance.",
        "Versace Pour Homme Oud Noir is an enigmatic and alluring fragrance that unveils the mystique of the Middle East. The opening notes of black pepper, lemon, and bergamot create a piquant intrigue, while the heart of rose, geranium, and cardamom unveils a touch of floral elegance. The true essence of the fragrance lies in its base notes of agarwood, leather, and patchouli, which exude an air of mystery and sensuality.",
        "Versace Eros is a vibrant and energetic fragrance that captures the essence of youthful passion. The opening notes of mint, lemon, and green apple invigorate the senses, while the heart of rosemary, ambroxan, and geranium exudes a fresh and modern masculinity. The concluding notes of vanilla, cedarwood, and Vetiver provide a touch of warmth and sophistication, making this fragrance a captivating choice for the modern gentleman.",
        "Versace Eros Flame is an ardent and seductive fragrance that ignites the senses with its fiery intensity. The opening notes of chinotto, lemon, and rosemary set the stage for an aromatic adventure, while the heart of pepper, black pepper, and geranium adds a touch of spice and intrigue. The concluding notes of vanilla, tonka bean, and cedarwood provide a warm and enticing embrace, making this fragrance perfect for the man who exudes confidence and charisma.",
        "Versace Pour femme Dylan Purple is an enchanting and feminine fragrance that captures the essence of a Mediterranean summer. The opening notes of black currant, apple, and Calabrian bergamot create a refreshing and vibrant accord, while the heart of freesia, jasmine, and peony unfolds a bouquet of delicate floral beauty. The concluding notes of cedarwood, cashmeran, and vanilla provide a touch of sophistication and warmth, leaving an unforgettable impression of elegance and grace.",
        "Do Son Eau de Toilette is a fresh, feminine fragrance that evokes the scent of a summer day by the sea. The tuberose is the star of the show, with its heady, intoxicating scent. The other notes, such as orange blossom, iris, and rose, provide a delicate balance and prevent the fragrance from becoming too overpowering.",
        "Oléne Eau de Toilette is a romantic and evocative fragrance that transports you to a Venetian garden in bloom. The narcissus and honeysuckle in the top notes are bright and cheerful, while the jasmine and wisteria in the middle notes add a touch of sweetness and mystery. The white flowers and green notes in the base are grounding and provide a long-lasting fragrance.",
        "Volutes Eau de Toilette is a warm, smoky fragrance that evokes the scent of a luxurious smoking lounge. The tobacco and honey in the top notes are rich and seductive, while the immortelle, saffron, and pink pepper in the middle notes add a touch of spice and intrigue. The benzoin, opoponax, myrrh, and styrax in the base are grounding and provide a long-lasting fragrance.",
        "Eau Capitale is a modern take on the classic chypre fragrance. It is a complex and sophisticated scent that is both elegant and alluring. The pink pepper and bergamot in the top notes add a touch of brightness and sparkle, while the rose in the middle note provides a romantic and feminine touch. The patchouli in the base adds depth and warmth, and it also helps to prolong the fragrance's wear time.",
        "Fleur de Peau Eau de Parfum is a sensual and intimate fragrance that evokes the feeling of bare skin. The musks are the star of the show, with their soft and inviting scent. The iris and ambrette seeds add a touch of elegance and sophistication, while the cottony and downy notes create a feeling of comfort and warmth.",
        "Philosykos Eau de Parfum is a fresh, green fragrance that captures the essence of a fig tree in summer. The fig leaf and fig notes in the top notes are bright and juicy, while the green notes and coconut in the middle notes add a touch of creaminess and sweetness. The fig tree, woody notes, and cedar in the base are grounding and provide a long-lasting fragrance.",
        "Ameer Al Oudh Intense Oud is a rich and luxurious fragrance that opens with woody notes and oud. The heart of the fragrance is a creamy and sweet blend of vanilla and sugar, while the base is dark and smoky with agarwood (oud), sandalwood, and herbal notes. This fragrance is perfect for those who love bold and exotic scents.",
        "Raghba is a warm and inviting fragrance that opens with notes of saffron and nutmeg. The heart of the fragrance is a rich blend of geranium, woody notes, and labdanum, while the base is anchored by oud, vanilla, and leather. This fragrance is perfect for those who love sensual and sophisticated scents.",
        "Oud Mood is a dark and mysterious fragrance that opens with notes of agarwood (oud) and woody notes. The heart of the fragrance is a smoky and leathery blend of tobacco and leather, while the base is deep and earthy with patchouli, amber, and musk. This fragrance is perfect for those who love intense and masculine scents.",
        "Fakhar Black is a bold and powerful fragrance that opens with notes of black pepper and cardamom. The heart of the fragrance is a spicy and woody blend of cinnamon, nutmeg, and clove, while the base is dark and mysterious with oud, leather, and musk. This fragrance is perfect for those who love confident and assertive scents.",
        "Ana Abiyedh is a delicate and feminine fragrance that opens with notes of white flowers and citrus. The heart of the fragrance is a soft and powdery blend of rose, jasmine, and iris, while the base is warm and comforting with vanilla, musk, and sandalwood. This fragrance is perfect for those who love romantic and elegant scents.",
        "Bade'e Al Oud Honor & Glory is a rich and opulent fragrance that opens with notes of agarwood (oud) and spices. The heart of the fragrance is a warm and woody blend of sandalwood, patchouli, and cedarwood, while the base is deep and luxurious with amber, musk, and vanilla. This fragrance is perfect for those who love traditional and sophisticated scents.",
    ]; // List of descriptions
  
    const perfumeList: PerfumeProps[] = [];
  
    for (let i = 0; i < names.length; i++) {
      const id = `perfume${i + 1}`;
      const stock = getRandomNumber(20, 40);
      const rating = 0;
      const bestSeller = i < 4; // Set bestSeller to true for the first 4 perfumes
  
      const perfume: PerfumeProps = {
        id,
        name: names[i],
        image: images[i],
        price: prices[i], // Remove commas and dots from price
        brand: brands[i],
        occasion: occasions[i],
        size: sizes[i],
        concentration: concentrations[i],
        origin: origins[i],
        topNotes: topNotes[i].split((',')),
        middleNotes: middleNotes[i].split((',')),
        baseNotes: baseNotes[i].split((',')),
        gender: genders[i],
        description: descriptions[i],
        stock,
        rating,
        reviews: [],
        bestSeller: bestSeller,
      };
  
      perfumeList.push(perfume);
    }
  
    return perfumeList;
  }
  
export function getBestSellerPerfumesFromLocal() {
    const perfumes = getPerfumeFromLocal();

    return perfumes.filter((perfume) => perfume.bestSeller == true);
}

export function getPerfumeByIdFromLocal(id: string) {
    const perfumes = getPerfumeFromLocal();
    return perfumes.find((perfume) => perfume.id == id);
}

  // Example usage:
//   const perfumeList = getPerfumeFromLocal();
//   console.log(perfumeList);